//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testpaper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CN_MatPaperType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CN_MatPaperType()
        {
            this.CN_PaperCode = new HashSet<CN_PaperCode>();
        }
    
        public int id { get; set; }
        public string paperTypeId { get; set; }
        public string pclass { get; set; }
        public string paperTypeName { get; set; }
        public string reamrk { get; set; }
        public Nullable<System.DateTime> invalidDate { get; set; }
        public string CREATER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string MODEIFIER { get; set; }
        public Nullable<System.DateTime> MODI_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CN_PaperCode> CN_PaperCode { get; set; }
    }
}
