//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testpaper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CN_PaperCode
    {
        public int id { get; set; }
        public System.DateTime issueDate { get; set; }
        public string code { get; set; }
        public int paperType { get; set; }
        public string cDesc { get; set; }
        public short r1 { get; set; }
        public short r2 { get; set; }
        public Nullable<int> avgWet { get; set; }
        public string remark { get; set; }
        public Nullable<bool> invalid { get; set; }
        public string createUser { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string modifyUser { get; set; }
        public Nullable<System.DateTime> modifyTime { get; set; }
    
        public virtual CN_MatPaperType CN_MatPaperType { get; set; }
    }
}
